# class Event
# gameplay events
extends Reference

enum event_type {CONSTRUCTION, FREE_POP, FREE_POP_NO_PROJECT, SPECIAL_ABILITY_INFO, SPECIAL_ABILITY_READY, RESEARCH_AVAILABLE, 
	RESEARCH_COMPLETE, SPACE_EXPLORATION, SPACE_EXPLORATION_INFO, RACE_SHIP_CONTACT, SHIP_SYSTEM_ARRIVAL, HOSTILE_SHIPS_REMAINING_MOVES}

var type = null

var images = []
var text = []

var buttons = []
var targets = []